# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-10 11:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('abtesting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filter',
            name='type',
            field=models.CharField(choices=[('INT', 'INT'), ('BOOL', 'BOOL'), ('FLOAT', 'FLOAT'), ('STRING', 'STRING')], default='INT', max_length=10, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
    ]
